#!/bin/bash

if [ ! -d "ca" ]; then
    echo "You must generate your CA's certs before running this script."
    exit 1
fi
rm -rf server
mkdir -p server

OPENSSLFILE_CA=securesysCA
OPENSSLFILE_SERVER=securesysServer

echo "Generating Web Server's Key..."
openssl genrsa -des3 -out ./server/${OPENSSLFILE_SERVER}.key 1024 -config ./openssl.cnf

echo ""
echo "Generating Web Server Cert Request..."
openssl req -new -key ./server/${OPENSSLFILE_SERVER}.key -out ./server/${OPENSSLFILE_SERVER}.csr -config ./openssl.cnf

echo ""
echo "Signing Web Server's Key with CA key..."
openssl ca -days 365 -in ./server/${OPENSSLFILE_SERVER}.csr -cert ./ca/${OPENSSLFILE_CA}.crt -keyfile ./ca/${OPENSSLFILE_CA}.key -out ./server/${OPENSSLFILE_SERVER}.crt -config ./openssl.cnf
chmod ugo-rwx,u+r server/${OPENSSLFILE_SERVER}.key
