#!/bin/bash

rm -rf ca
mkdir -p ca

#Design DB for OpenSSL to keep track of certs
echo "01" > ca/serial
touch ca/index.txt

#Define used vars
OPENSSLFILE_CA=securesysCA
DIR=`pwd`

#Generate CA key
echo ""
echo "Generating CA's Key..."
openssl genrsa -out ca/${OPENSSLFILE_CA}.key 1024 

#Generate self signed CA cert
openssl req -config openssl.cnf -key ca/${OPENSSLFILE_CA}.key -new -x509 -days 365 -sha256 -extensions v3_ca -out ca/${OPENSSLFILE_CA}.crt

#Make CA key private via permission change
chmod ugo-rwx,u+r ca/${OPENSSLFILE_CA}.key
